spring:
  config:
    activate:
      on-profile: "qa"

  build:
    version: "v0.0.2"

support:
  message: "Bienvenidos al sistema de cuentas bancarias de Accenture - Sistema de pruebas (Modificado 1 desde GIT)"
  contactInfo:
    name: "QA"
    email: "product.tester@prueba_qa.com"
  phoneNumbers:
    - (57) 301
    - (57) 300
